version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - godot
    - godox
    - gosec
    - gosmopolitan
    - govet
    - ineffassign
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nilerr
    - nilnesserr
    - noctx
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - unparam
    - unused
    - zerologlint
  settings:
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: argument-limit
          arguments:
            - 6
          severity: warning
          disabled: false
        - name: confusing-naming
          disabled: true
        - name: confusing-results
          disabled: true
        - name: cyclomatic
          arguments:
            - 7
          disabled: true
        - name: file-header
          disabled: true
        - name: line-length-limit
          arguments:
            - 80
          severity: warning
          disabled: true
        - name: function-length
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: banned-characters
          disabled: true
        - name: function-result-limit
          arguments:
            - 3
          severity: warning
          disabled: false
        - name: flag-parameter
          disabled: true
        - name: package-comments
          disabled: true
    wsl:
      allow-cuddle-declarations: true
      force-err-cuddling: true
      force-short-decl-cuddling: true
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
